version: '3'
services:
  redis:
    image: redis:latest
    volumes:
      - ./data/redis-data:/data
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A app_celery.celery worker --loglevel=info