version: '3'
services:
  app:
    image: p310:v1.0
    ports:
      - 8000:8000
    network_mode: host
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  celery-worker:
    image: p310:v1.0
    volumes:
      - .:/app
    network_mode: host
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    command: celery -A app_celery.celery worker