version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    command: celery -A app_celery.celery worker

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    command: celery -A app_celery.celery beat