login_response = {'data': {
    'token': {'accessToken': 'OgjDSY1nbUIu8IKbcz2DHo', 'refreshToken': 'cLdsk68tZ5Tu95aHDLcY3V', 'ttl': 899,
              'refreshTtl': 7776000, 'scope': 'AUTHZ_GUEST_SECURED_SESSION', 'authenticator': 'CUR',
              'tokenType': 'bearer', 'assertionType': 'consumer-direct',
              'swid': '{79f82313-f468-4199-a64c-dd0c8a0d9fd1}', 'clientId': 'DPRD-SHDR.MOBILE.ANDROID-PROD',
              'expireAt': 1715348887415},
    'profile': {'swid': '{79f82313-f468-4199-a64c-dd0c8a0d9fd1}', 'mobileAreaNum': '86', 'mobileCountryISO2': 'CN',
                'mobile': '19807910929', 'email': '', 'firstName': '卡卡', 'lastName': '卡', 'residenceCountryISO2': '',
                'ageBand': 'ADULT', 'shdrMktFamilyOptIn': '0', 'shdrMktOptIn': '0', 'personalizedRecoOptIn': True,
                'touStatus': True, 'verifyStatus': True, 'psnPass': 1,
                'characterVal': 'elsa;entityType=Avatar;destination=shdr', 'lastLoginTimestamp': '2024-05-10',
                'loginTimestamp': '2024-05-10', 'status': 'ACTIVE', 'communicationPreference': '1',
                'registrationDate': '2023-01-24', 'swidType': 'Full', 'province': '', 'hasFirstName': True,
                'hasLastName': True, 'loginType': 'mobile', 'isMember': True,
                'memberConsentTime': '2023-12-30 16:11:54'}}, 'errors': []}

eligible_response = {'code': 200, 'message': 'success', 'meta': {'timestamp': '2024-05-11 07:42:20'}, 'data': {
    'eligible': [{'visualId': '0052020960061563005', 'startDateTime': '2024-05-18T07:00:00',
                  'endDateTime': '2024-05-18T23:00:00', 'category': 'ThemePark', 'availableDateList': ['2024-05-18'],
                  'name': '标准票1日票', 'visualIdMask': '0052020960061563005', 'imageurl': '', 'guestName': '',
                  'expireTime': '2024年05月18日', 'expireStartTime': '2024-05-18', 'expireEndTime': '2024-05-18',
                  'canUsed': True}], 'nonEligible': [
        {'visualId': '0001408637050007207', 'startDateTime': '2023-02-27T00:00:00',
         'endDateTime': '2024-03-13T23:59:59', 'category': 'AnnualPass',
         'assignedGuest': {'firstName': '*', 'lastName': '卡如'}, 'name': '无限钻石卡 - 标准',
         'visualIdMask': '*************007207',
         'imageurl': 'https://static.shanghaidisneyresort.com/web-img-gallery/anydaywechatProductImage.png',
         'guestName': '* 卡如', 'expireTime': '2023年02月27日-2024年03月13日', 'canUsed': False},
        {'visualId': '4726090081410637604', 'startDateTime': '2024-01-16T00:00:00',
         'endDateTime': '2024-07-16T23:59:00', 'category': 'ThemePark',
         'assignedGuest': {'firstName': '*', 'lastName': None}, 'name': '标准1日票',
         'visualIdMask': '4726090081410637604', 'imageurl': '', 'guestName': '',
         'expireTime': '2024年01月16日-2024年07月16日', 'canUsed': False},
        {'visualId': '8042309271664167003', 'startDateTime': '2024-01-16T00:00:00',
         'endDateTime': '2024-07-16T23:59:00', 'category': 'ThemePark',
         'assignedGuest': {'firstName': '*', 'lastName': None}, 'name': '标准1日票',
         'visualIdMask': '8042309271664167003', 'imageurl': '', 'guestName': '',
         'expireTime': '2024年01月16日-2024年07月16日', 'canUsed': False},
        {'visualId': '0801163396006447276', 'startDateTime': '2024-01-16T00:00:00',
         'endDateTime': '2024-07-16T23:59:00', 'category': 'ThemePark',
         'assignedGuest': {'firstName': '*', 'lastName': None}, 'name': '标准1日票',
         'visualIdMask': '0801163396006447276', 'imageurl': '', 'guestName': '',
         'expireTime': '2024年01月16日-2024年07月16日', 'canUsed': False},
        {'visualId': '2002562930660009277', 'startDateTime': '2024-05-02T07:00:00',
         'endDateTime': '2024-05-02T23:00:00', 'category': 'ThemePark',
         'assignedGuest': {'firstName': '*', 'lastName': None}, 'name': '一日票含礼宾服务豪华套装A',
         'visualIdMask': '2002562930660009277', 'imageurl': '', 'guestName': '', 'expireTime': '2024年05月02日',
         'canUsed': False}, {'visualId': '7206200005220460060', 'startDateTime': '2024-05-02T07:00:00',
                             'endDateTime': '2024-05-02T23:00:00', 'category': 'ThemePark',
                             'assignedGuest': {'firstName': '*', 'lastName': None}, 'name': '一日票含礼宾服务豪华套装A',
                             'visualIdMask': '7206200005220460060', 'imageurl': '', 'guestName': '',
                             'expireTime': '2024年05月02日', 'canUsed': False},
        {'visualId': '0612103524500028367', 'startDateTime': '2024-05-02T07:00:00',
         'endDateTime': '2024-05-02T23:00:00', 'category': 'ThemePark',
         'assignedGuest': {'firstName': '*', 'lastName': None}, 'name': '一日票含礼宾服务豪华套装A',
         'visualIdMask': '0612103524500028367', 'imageurl': '', 'guestName': '', 'expireTime': '2024年05月02日',
         'canUsed': False}, {'visualId': '1120046332200638052', 'startDateTime': '2024-05-02T07:00:00',
                             'endDateTime': '2024-05-02T23:00:00', 'category': 'ThemePark',
                             'assignedGuest': {'firstName': '*', 'lastName': None}, 'name': '一日票含礼宾服务豪华套装A',
                             'visualIdMask': '1120046332200638052', 'imageurl': '', 'guestName': '',
                             'expireTime': '2024年05月02日', 'canUsed': False},
        {'visualId': '6000000260862022104', 'startDateTime': '2024-05-04T07:00:00',
         'endDateTime': '2024-05-04T23:00:00', 'category': 'ThemePark',
         'assignedGuest': {'firstName': '*', 'lastName': None}, 'name': '标准票1日票',
         'visualIdMask': '6000000260862022104', 'imageurl': '', 'guestName': '', 'expireTime': '2024年05月04日',
         'canUsed': False}, {'visualId': '3120112314000009301', 'startDateTime': '2024-05-04T07:00:00',
                             'endDateTime': '2024-05-04T23:00:00', 'category': 'ThemePark',
                             'assignedGuest': {'firstName': '*', 'lastName': None}, 'name': '标准票1日票',
                             'visualIdMask': '3120112314000009301', 'imageurl': '', 'guestName': '',
                             'expireTime': '2024年05月04日', 'canUsed': False}], 'linked': True}}

morning_price_response = {'code': 200, 'message': 'success', 'meta': {'timestamp': '2024-05-11 07:56:46'}, 'data': [
    {'id': 'shdr-early-park-entry-pass_2018-12-01_1_ST_0_0_RF_AF_SOF_41', 'text': '早享卡', 'price': '189',
     'group': 'standard', 'plu': 'SHCP01OLPKVC1901P', 'eventId': 65824, 'resourceId': 110, 'unitPrice': '189',
     'description': '乐园早享卡', 'sku': 'SHCP01OLPKVC1901P', 'startDateTime': '2024-05-18T05:00:00.000+08:00',
     'subtotal': '189', 'currency': 'CNY', 'tax': '0', 'taxIncluded': False, 'capacityManaged': True,
     'productType': 'shdr-early-park-entry-pass'}]}

morning_confirm_response = {'code': 200, 'message': 'success', 'meta': {'timestamp': '2024-05-11 08:15:52'},
                            'data': {'orderId': '06dbef3b-8a4b-497d-bb29-15ad4bf371da',
                                     'paymentSessionId': '1320ae002d6fa5af36c2abb385aecf06'}}

morning_date_check_response = {'code': 200, 'message': 'success', 'meta': {'timestamp': '2024-05-11 08:20:44'},
                               'data': {'title': [{'name': '2024-05', 'text': '<b>2024年 5月</b>'}],
                                        'data': [{'date': '2024-05-12', 'price': '149', 'soldOut': False},
                                                 {'date': '2024-05-13', 'price': '189', 'soldOut': False},
                                                 {'date': '2024-05-14', 'price': '189', 'soldOut': False},
                                                 {'date': '2024-05-15', 'price': '189', 'soldOut': False},
                                                 {'date': '2024-05-16', 'price': '189', 'soldOut': False},
                                                 {'date': '2024-05-17', 'price': '189', 'soldOut': False},
                                                 {'date': '2024-05-18', 'price': '189', 'soldOut': False}]}}

transaction_response = {'href': 'https://openapi.alipay.com/gateway.do?charset=utf-8', 'params': {
    'response_text': 'YXBwX2lkPTIwMTkxMDI5Njg3MzE3NjcmYml6X2NvbnRlbnQ9JTdCJTIyb3V0X3RyYWRlX25vJTIyJTNBJTIyMjAyNDA1MTEwNTAxMDAwNjA2ODYlMjIlMkMlMjJwcm9kdWN0X2NvZGUlMjIlM0ElMjJRVUlDS19NU0VDVVJJVFlfUEFZJTIyJTJDJTIydG90YWxfYW1vdW50JTIyJTNBJTIyMTg5LjAwJTIyJTJDJTIyc3ViamVjdCUyMiUzQSUyMiVFNCVCOCU4QSVFNiVCNSVCNyVFOCVCRiVBQSVFNSVBMyVBQiVFNSVCMCVCQyVFNSVCQSVBNiVFNSU4MSU4NyVFNSU4QyVCQSVFNCVCQSVBNyVFNSU5MyU4MSUyMiUyQyUyMnBhc3NiYWNrX3BhcmFtcyUyMiUzQSUyMjE2MzM3MDgzJTIyJTJDJTIydGltZW91dF9leHByZXNzJTIyJTNBJTIyMTltJTIyJTJDJTIyZXh0ZW5kX3BhcmFtcyUyMiUzQSU3QiUyMnN5c19zZXJ2aWNlX3Byb3ZpZGVyX2lkJTIyJTNBJTIyMjA4ODEyMTg1MDU0OTYzMCUyMiU3RCU3RCZjaGFyc2V0PXV0Zi04Jm1ldGhvZD1hbGlwYXkudHJhZGUuYXBwLnBheSZub3RpZnlfdXJsPWh0dHBzJTNBJTJGJTJGcHJvZC5vcmlnaW4tcG13LnNoYW5naGFpZGlzbmV5cmVzb3J0LmNvbSUyRmdsb2JhbC1wb29sLW92ZXJyaWRlLUElMkZwYXltZW50LW1pZGRsZXdhcmUtc2VydmljZSUyRnRyYW5zYWN0aW9uJTJGYWxpcGF5JTJGY29uZmlybSUyRjE2MzM3MDgzJnNpZ249SEk3eVNORGVrdTclMkJOTVVJRHdudGE0c3g2SjVIJTJCaENzSFhCJTJGM0xjUllubXl0cFIwMjJZWW4lMkY3YjJYcFNrVGx2RVIwSFFVVERkRDJaSkdGQjdNZjlkVU9LakhkdGlBUDVZVjFaR21qaWpPUTZseWNPbFNGNmtnRVdtUjNyNWl3QTJrc24lMkZ1YWRDWUNMaFY2S3gwVWUxdDJld3RBTjdhUlVKYm01ZW44aE5Eek1qOWlYZFclMkJuRVlBY0E1RzZNVXh0MkZReDBYajBrSW1vNVZreFJwYzBZbkxQSVpPRCUyQjJ0QWh1M2k0N2Y5ZmpuaExLTnFNUkU1ZVRHVklyMUx2WmRLZEVoN05wS1A4MXc3TkY1TEg5Y3cyQ3RFSFZQc1NpU3JKMEwxTTdvVmxWckRaZjlZcHh1VGxvZ2h2NVA2WGc1ZVcwa0YxczhpVWtIeGZkSzJJT1FHZlElM0QlM0Qmc2lnbl90eXBlPVJTQTImdGltZXN0YW1wPTIwMjQtMDUtMTErMTglM0EwNyUzQTExJnZlcnNpb249MS4w'},
                        'method': 'POST'}

check_one_day_response = {'id': 'shdr-theme-park-tickets', 'headerTitle': '乐园门票', 'date': {'title': '选择到访日期',
                                                                                               'headerDescription': '游客可于原定入园日零点的48小时前更换两次等值或者更高价值的本产品（例如常规日门票更换为特别常规日门票），条件是新的日期尚还有余票。如需更换更高价值的本产品，请在上述规定的时间内致电上海迪士尼度假区预定服务中心(电话：400-180-0000或86-21-3158-0000)并补足差价。',
                                                                                               'calendar': {'title': [
                                                                                                   {'name': '2024-05',
                                                                                                    'text': '2024年 5月'},
                                                                                                   {'name': '2024-06',
                                                                                                    'text': '2024年 6月'}],
                                                                                                   'data': [{
                                                                                                       'date': '2024-05-17',
                                                                                                       'available': True,
                                                                                                       'price': '599',
                                                                                                       'skuList': [
                                                                                                           'SHTP01OLSDQO',
                                                                                                           'SHTP01OLCDQO',
                                                                                                           'SHTP01OLDDQO',
                                                                                                           'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-18',
                                                                                                           'available': False,
                                                                                                           'price': '599'},
                                                                                                       {
                                                                                                           'date': '2024-05-19',
                                                                                                           'available': True,
                                                                                                           'price': '599',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-20',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-21',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-22',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-23',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-24',
                                                                                                           'available': True,
                                                                                                           'price': '599',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-25',
                                                                                                           'available': True,
                                                                                                           'price': '599',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-26',
                                                                                                           'available': True,
                                                                                                           'price': '599',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-27',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-28',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-29',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-30',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-05-31',
                                                                                                           'available': True,
                                                                                                           'price': '599',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-01',
                                                                                                           'available': True,
                                                                                                           'price': '719',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-02',
                                                                                                           'available': True,
                                                                                                           'price': '599',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-03',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-04',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-05',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-06',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-07',
                                                                                                           'available': True,
                                                                                                           'price': '599',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-08',
                                                                                                           'available': True,
                                                                                                           'price': '719',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-09',
                                                                                                           'available': True,
                                                                                                           'price': '719',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-10',
                                                                                                           'available': True,
                                                                                                           'price': '599',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLRDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-11',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-12',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-13',
                                                                                                           'available': True,
                                                                                                           'price': '475',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLRDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLSDQO']},
                                                                                                       {
                                                                                                           'date': '2024-06-14',
                                                                                                           'available': True,
                                                                                                           'price': '599',
                                                                                                           'skuList': [
                                                                                                               'SHTP01OLSDQO',
                                                                                                               'SHTP01OLCDQO',
                                                                                                               'SHTP01OLDDQO',
                                                                                                               'SHTP01OLRDQO']}],
                                                                                                   'current': '2024-05-17'},
                                                                                               'footerDescription': '',
                                                                                               'soldOutText': '已售罄',
                                                                                               'todayText': '今天',
                                                                                               'soldOutReminderText': '已售罄状态只表示当下产品的库存状态，会根据此产品游客的下单状态进行更新。',
                                                                                               'displayOrder': 1},
                          'selectNumber': {'title': '选择门票数量', 'importantNote': {'title': '票价定义标准',
                                                                                      'popupId': 'tickets.bookPage.partyMix.dayticket.importantNote.content'},
                                           'headerDescription': '每笔订单最多只能预订5张门票。', 'partyMix': [
                                  {'ageGroup': 'adult', 'text': '标准票',
                                   'subText': '游园当日身高1.4米以上，12-59周岁（含）',
                                   'id': 'shdr-theme-park-tickets_2017-04-20_1_A_0_0_RF_AF_SOF_41', 'price': '599',
                                   'defaultNum': '1', 'maxNum': 5, 'minNum': 0, 'group': 'adult', 'plu': 'SHTP01OLRDQO',
                                   'eventId': 64237, 'resourceId': 1, 'unitPrice': '599',
                                   'description': '一日票 - 标准票', 'sku': 'SHTP01OLRDQO',
                                   'startDateTime': '2024-05-17T07:00:00.000+08:00', 'subtotal': '599',
                                   'currency': 'CNY', 'tax': '0', 'taxIncluded': False},
                                  {'ageGroup': 'child', 'text': '儿童票',
                                   'subText': '游园当日年龄在3周岁（含）至11周岁（含）；或身高1.0米以上至1.4米（含1.4米）',
                                   'id': 'shdr-theme-park-tickets_2017-04-20_1_C_0_0_RF_AF_SOF_41', 'price': '449',
                                   'defaultNum': '0', 'maxNum': 5, 'minNum': 0, 'group': 'child', 'plu': 'SHTP01OLCDQO',
                                   'eventId': 64237, 'resourceId': 1, 'unitPrice': '449',
                                   'description': '一日票 - 儿童票', 'sku': 'SHTP01OLCDQO',
                                   'startDateTime': '2024-05-17T07:00:00.000+08:00', 'subtotal': '449',
                                   'currency': 'CNY', 'tax': '0', 'taxIncluded': False},
                                  {'ageGroup': 'senior', 'text': '老年票', 'subText': '游园当日60周岁及以上',
                                   'id': 'shdr-theme-park-tickets_2017-04-20_1_S_0_0_RF_AF_SOF_41', 'price': '449',
                                   'defaultNum': '0', 'maxNum': 5, 'minNum': 0, 'group': 'senior',
                                   'plu': 'SHTP01OLSDQO', 'eventId': 64237, 'resourceId': 1, 'unitPrice': '449',
                                   'description': '一日票 - 老年票', 'sku': 'SHTP01OLSDQO',
                                   'startDateTime': '2024-05-17T07:00:00.000+08:00', 'subtotal': '449',
                                   'currency': 'CNY', 'tax': '0', 'taxIncluded': False},
                                  {'ageGroup': 'disabled', 'text': '残障票', 'subText': '持有效残障证明的游客',
                                   'id': 'shdr-theme-park-tickets_2021-10-08_1_D_0_0_RF_AF_SOF_41', 'price': '449',
                                   'defaultNum': 0, 'maxNum': 5, 'minNum': 0, 'group': 'disabled',
                                   'plu': 'SHTP01OLDDQO', 'eventId': 64237, 'resourceId': 1, 'unitPrice': '449',
                                   'description': '一日票 - 残障票', 'sku': 'SHTP01OLDDQO',
                                   'startDateTime': '2024-05-17T07:00:00.000+08:00', 'subtotal': '449',
                                   'currency': 'CNY', 'tax': '0', 'taxIncluded': False}],
                                           'numberValidate': {'maxNumber': 5, 'minNumber': 1,
                                                              'validateMaxMsg': '每笔订单最大预定数为5',
                                                              'validateMinMsg': '每笔订单最小预定数为1'},
                                           'footerDescription': '<b>入园注意事项：</b><br>\n残障人士须携带本人有效身份证原件及本人有效残障证明原件，在主入口通过“中国残疾人联合会”微信公众号的“证件查询”页面验证本人的残疾证后方可入园。入园时无法出示本人的有效残障证明原件，或无法通过页面验证的游客，须按标准票的全价补全差价。',
                                           'displayOrder': 2}, 'getCoupon': {'text': '有优惠券可以领取'},
                          'checkout': {'totalText': '总计', 'confirmButton': '立即购买'}, 'soldOutText': '已售罄',
                          'capacityManaged': True, 'disabledReminder': {'title': '残障票注意事项',
                                                                        'content': '<b>残障票适用对象：</b><br> 持有效残障证明的游客。<br><br> <b>入园注意事项：</b><br>残障人士须携带本人有效身份证原件及本人有效残障证明原件，在主入口通过“中国残疾人联合会”微信公众号的“证件查询”页面验证本人的残疾证后方可入园。入园时无法出示本人的有效残障证明原件，或无法通过页面验证的游客，须按标准票的全价补全差价。',
                                                                        'closeButton': '确定'},
                          'greenPointToggle': 'true', 'couponUsable': '可用优惠券',
                          'couponUsableStatementTitle': '所选日可用优惠',
                          'couponUsableStatement': '所展示的信息为当前产品全部可用券，不代表您当前持有该券。实际可用券以领取后的为准',
                          'noCouponsToUse': '所选日暂无可用优惠', 'unifiedExpressCheckout': True,
                          'btns': {'btnAdd': '加入购物车', 'btnCancel': '取消', 'btnConfirm': '确认'},
                          'apReminder': {'title': '请选择您的年卡支付方式',
                                         'message': '如您选择全额支付，您的年卡产品将被添加到购物车中并与其他商品一起支付。<br>如您选择分期付款，我们将会先为您完成年卡产品的购买流程。',
                                         'btnCancel': '分期支付', 'btnConfirm': '全额支付'},
                          'editCancelReminder': {'title': '更改未保存',
                                                 'message': '您确认退出当前页面吗？您所做的更改尚未保存',
                                                 'btnCancel': '退出，不保存', 'btnConfirm': '继续编辑'},
                          'addToCart': True}

get_one_day_mock_response = {'originTotalAmount': 1198, 'totalPrice': 1198, 'totalAmount': 1198,
                             'totalPaymentAmount': 1198, 'bookNow': True, 'orderType': 'TICKETING',
                             'priceChange': False, 'tickets': [
        {'itemId': '588941377920827392', 'productCategoryId': 'ThemePark', 'productTypeId': 'shdr-theme-park-tickets',
         'productUnitLabel': None, 'icons': {'native': '0xE0C2', 'hybrid': 'di-tickets'},
         'productGroupId': 'ticket-group-shdr-theme-park-tickets-one-day-ticket-hybrid',
         'canUseStartDateTime': '2024-05-19T07:00:00.000+08:00', 'canUseEndDateTime': '2024-05-19T23:00:00.000+08:00',
         'originTotalAmount': 1198, 'totalPrice': 1198, 'totalAmount': 1198, 'totalPaymentAmount': 1198,
         'discountAmount': None, 'netpaymentAmount': None, 'sort': 1715863211035, 'startDate': '2024-05-19',
         'endDate': None, 'displayDate': '2024年05月19日', 'groupName': '一日票', 'numDays': None,
         'capacityManaged': True, 'detail': [
            {'sku': 'SHTP01OLRDQO', 'unitPrice': 599, 'originUnitPrice': 599, 'currency': '元', 'quantity': 2,
             'description': '一日票 - 标准票', 'groupItemLabel': '标准票', 'discountAmount': None,
             'netpaymentAmount': None, 'totalDiscountAmount': None, 'converseAmount': None}],
         'textLabels': {'roomprice': '房间价格', 'children': '儿童', 'withbreakfast': '含早餐',
                        'withAddons': '含{n}件附加产品', 'guest': '宾客', 'confirmation': '确认号：',
                        'packageprice': '房间含早价格', 'withBreakfastAndAddons': '含早餐及{n}件附加产品',
                        'servicecharge': '服务费'}, 'goodsTag': None, 'realNameQuantity': 0}], 'hotels': [],
                             'coupons': [], 'availableCoupons': [], 'unavailableCoupons': [],
                             'preCalculationNo': 'PRE011114329625268224', 'couponVid': None, 'useCoupon': True,
                             'paymentSource': 'TICKETING', 'goodsTag': None}

order_response = {'code': 200, 'message': 'success', 'meta': {'timestamp': '2024-05-16 13:09:59'},
                  'data': {'orderNumber': 'SC011114446742490112',
                           'paymentSessionId': '436d8df13e103d59faf8b416064e4d09', 'totalPaymentAmount': 1198,
                           'paymentSource': 'TICKETING', 'paymentOrderType': 'CART'}}
